---
#############################
# Gather environment stuff
#############################

- include_vars: "/opt/docker/etc/application.{{ PROVISION_CONTEXT }}.yml"

#############################
# Run tasks
#############################

- include: entrypoint/mysql.yml
