version: '2'

services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
#    links:
      #- mail
#      - mysql
      #- postgres
      #- solr
      #- elasticsearch
      #- redis
      #- memcached
      #- ftp
    external_links:
      - dev_mariadb:mariadb
    networks:
      - default
    ports:
      - "8001:80"
      #- "8443:443"
      - "10022:22"
      - "9001:9000"
    volumes:
       - ./app/:/app/
      - /tmp/debug/:/tmp/debug/
      - ./:/docker/
    volumes_from:
      - storage
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      VIRTUAL_HOST: "docker.vm"
      VIRTUAL_PORT: "80"
      POSTFIX_RELAYHOST: "[mail]:1025"


  #######################################
  # MySQL server
  #######################################
#  mysql:
#    build:
#      context: docker/mysql/
#      #dockerfile: MySQL-5.5.Dockerfile
#      dockerfile: MySQL-5.6.Dockerfile
#      # dockerfile: MySQL-5.7.Dockerfile
#      #dockerfile: MariaDB-5.5.Dockerfile
#      #dockerfile: MariaDB-10.Dockerfile
#      #dockerfile: Percona-5.5.Dockerfile
#      #dockerfile: Percona-5.6.Dockerfile
#      #dockerfile: Percona-5.7.Dockerfile
#    container_name: mysql
#    ports:
#      - 13306:3306
#    volumes_from:
#      - storage
#    volumes:
#      - /mnt/sda1/mysql_dev/db:/var/lib/mysql
#      - /tmp/debug/:/tmp/debug/
#    env_file:
#      - etc/environment.yml
#      - etc/environment.development.yml

  #######################################
  # PostgreSQL server
  #######################################
  #postgres:
  #  build:
  #    context: docker/postgres/
  #    dockerfile: Postgres-9.4.Dockerfile
  #    dockerfile: Postgres-9.5.Dockerfile
  #  ports:
  #    - 15432:5432
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml

  #######################################
  # Solr server
  #######################################
  #solr:
  #  build:
  #    context: docker/solr/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml
  #  environment:
  #    - SOLR_STORAGE=/storage/solr/server-master/
  #    - VIRTUAL_HOST=solr.boilerplate.docker
  #    - VIRTUAL_PORT=8983

  #######################################
  # Elasticsearch
  #######################################
  #elasticsearch:
  #  build:
  #    context: docker/elasticsearch/
  #  ports:
  #    - 19200:9200
  #    - 19300:9300
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml
  #  environment:
  #    - VIRTUAL_HOST=elasticsearch.boilerplate.docker
  #    - VIRTUAL_PORT=9200

  #######################################
  # Redis
  #######################################
  #redis:
  #  build:
  #    context: docker/redis/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: docker/memcached/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml

  #######################################
  # Mail
  #######################################
  # Mailhog
#  mail:
#     image: mailhog/mailhog
#   #  ports:
#   #    - 8025:8025
#     environment:
#      - VIRTUAL_HOST=mail.boilerplate.docker
#      - VIRTUAL_PORT=8025

  # Mailcatcher
  #mail:
  #  image: schickling/mailcatcher
  #  environment:
  #    - VIRTUAL_HOST=mail.boilerplate.docker
  #    - VIRTUAL_PORT=1080


  # Mailsandbox
  #mail:
  #  image: webdevops/mail-sandbox
  #  environment:
  #    - VIRTUAL_HOST=mail.boilerplate.docker
  #    - VIRTUAL_PORT=80

  #######################################
  # FTP (vsftpd)
  #######################################
  #ftp:
  #  build:
  #    context: docker/vsftpd/
  #  volumes_from:
  #    - storage
  #  volumes:
  #    - ./:/application/
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml

  #######################################
  # phpMyAdmin
  #######################################
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - mysql
#    ports:
#      - 8001:80
#    environment:
#      - PMA_ARBITRARY=1
#      - VIRTUAL_HOST=pma.boilerplate.docker
#      - VIRTUAL_PORT=80
#    volumes:
#      - /sessions

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage

#  nginx-proxy:
#    image: jwilder/nginx-proxy:latest
#    container_name: nginx_proxy
#    ports:
#     - 80:80
#     # - 443:443
#    volumes:
#     - //var/run/docker.sock:/tmp/docker.sock:ro
#     # - vhost.d:/etc/nginx/vhost.d:ro
#    restart: always
#    networks:
#      - default

networks:
  default:
    external:
      name: dev
